# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghd2i < Formula
  desc "Create GitHub Issues from GitHub Discussions
"
  homepage "https://github.com/suzuki-shunsuke/ghd2i"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.2.0/ghd2i_darwin_amd64.tar.gz"
      sha256 "42a335b6a41135cf80ef8b2c5ded3f42e4ade7052965152a96a9205be8ec8544"

      def install
        bin.install "ghd2i"
        generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.2.0/ghd2i_darwin_arm64.tar.gz"
      sha256 "44cf0a45867a4ced7607618db505216689a8fed960ae1b15ac6ba566fb23bfb8"

      def install
        bin.install "ghd2i"
        generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.2.0/ghd2i_linux_amd64.tar.gz"
        sha256 "a0d2504b71bd218dee41d8bc8ff277b3fdfc57ee0dcc3065fde9192faad5afc8"

        def install
          bin.install "ghd2i"
          generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.2.0/ghd2i_linux_arm64.tar.gz"
        sha256 "b512a0f864c978ea7577efcfe1b0f38b6380c02f75e2e9647272254412a62330"

        def install
          bin.install "ghd2i"
          generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghd2i --version"
  end
end
