# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghd2i < Formula
  desc "Create GitHub Issues from GitHub Discussions
"
  homepage "https://github.com/suzuki-shunsuke/ghd2i"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.1.1/ghd2i_darwin_amd64.tar.gz"
      sha256 "a04901ec0564d8536f7a85e8ffdf404c766e17f6a81db231989d9b279cdc526d"

      def install
        bin.install "ghd2i"
        generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.1.1/ghd2i_darwin_arm64.tar.gz"
      sha256 "fef880198c3bba01a8fdb14869143cdbdc7c678b122278cb8df97b7e5445e40c"

      def install
        bin.install "ghd2i"
        generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.1.1/ghd2i_linux_amd64.tar.gz"
        sha256 "d642a76aa08ba02ff90cb32907223db983818805234e6745aea4fadbe16ef9ea"

        def install
          bin.install "ghd2i"
          generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghd2i/releases/download/v0.1.1/ghd2i_linux_arm64.tar.gz"
        sha256 "f655ca253d86ff59de6edd9a8630835519a322358444f59931f53e17897c7791"

        def install
          bin.install "ghd2i"
          generate_completions_from_executable(bin/"ghd2i", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/ghd2i --version"
  end
end
